# ...existing code...
class CodeGenerator:
    # ...existing code...
    def _generate_step(self, step):
        # ...existing code...
        chain = f"api.{step.method.lower()}('{step.url}')"
        # ...existing code for auth, headers, payload, etc...
        # Retry
        if getattr(step, 'retry_count', 0) > 0:
            chain += f".retry({step.retry_count}, mode='{step.retry_mode}', backoff={step.retry_backoff})"
        # ...existing code for assertions, extractions, etc...
        return chain
# ...existing code...
